openapi: 3.0.3
info:
  title: Notes Server
  description: 'Выполненое задание 2 для олимпиады Я-Профессионал по направлению "Программная инженерия". Выполнил Измайлов Александр'
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /notes:
    parameters:
      - in: query
        name: query
        required: false
        schema:
          type: string
        description: "Строка для поиска по заметкам"
    get:
      description: 'Возвращает список всех заметок'
      responses:
        200:
          description: 'OK. В ответе передан список всех заметок или список заметок подходяших под запрос `query`. Все поля не пустые'
          content:
            application/json:
              example:
                - id: 10
                  title: "Список дел"
                  content: "Сделать ДЗ"
                - id: 12
                  title: "Фильмы которы"
                  content: "Фильмы которые я хочу посмотреть"
        204:
          description: 'В системе еще нет заметок или `query` не подходит ни под одну заметку, ответ пустой'
        400:
          description: '`query` является невалидной строкой'
    post:
      description: 'Создает новую заметку в системе'
      requestBody:
        description: 'В запросе нужно передать имя заметки(опционально) и ее содержимое'
        content:
          application/json:
            schema:
              type: object
            examples:
              'Новая заметка':
                value:
                  title: Имя заметки
                  content: Содержимое заметки
              'Заметка без имени':
                value:
                  content: Содержимое заметки
        required: true

      responses:
        201:
          description: 'Заметка создана. Заметке из запроса присвоен идентификатор'
          content:
            application/json:
              examples:
                'Результат создания':
                  $ref: '#/components/examples/simle_note'
        400:
          description: 'Неверное содержимое запроса. Или неправильный объект JSON(неизвестные поля)'
  '/notes/{id}':
    get:
      parameters:
        - $ref: '#/components/parameters/id'
      description: 'Возвращает заметку с данным идентификатором'
      responses:
        200:
          description: 'Заметка с таким id существует'
          content:
            application/json:
              examples:
                'Существующая заметка':
                  $ref: '#/components/examples/simle_note'
        204:
          description: 'Заметки с таким идентификатором нет'
    put:
      parameters:
        - $ref: '#/components/parameters/id'
      description: 'Изменяет существующую заметку'
      requestBody:
        required: true
        content:
          application/json:
            example:
              title: Новое имя
              content: Новое содержимое
            schema:
              type: object
      responses:
        200:
          description: 'Заметка с таким id существует и изменения валидны'
          content:
            application/json:
              example:
                title: Новое имя
                content: Новое содержимое
                id: 10
        404:
          description: 'Заметки с таким id не существует'
        400:
          description: 'Изменение является не валидным JSON'
    delete:
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: 'Заметка удалена'
          content:
            application/json:
              example:
                id: 10





components:
  parameters:
    id:
      in: path
      name: id
      schema:
        type: integer
      required: true
      description: 'Идентификатор заметки'

  examples:
    simle_note:
      value:
        id: 10
        title: "Имя заметки"
        content: "Содержимое заметки"
